time              timestamp         # Timestamp corresponds to the timestamp
                                    # of image header if image exists

ElementFloat64[]  float64_list      # List of chunk with datatype float
ElementInt64[]    int64_list        # List of chunk with datatype integer
ElementBool[]     bool_list         # List of chunk with datatype boolean
ElementString[]   string_list       # List of chunk with datatype string
