string  trigger_selector    # Trigger selection: FrameStart, ...
string  trigger_source      # Trigger source: Software, ...
float64 trigger_delayus     # Delay before triggered in microsecs
bool    value               # true to enable, false to disable
---
